### PR TITLE
do basic auth correct

### LINKED ISSUE #8: Login fails when passwords have @ character
Login fails when passwords have `@` character mainly due to how the request URL is being built in https://github.com/medic/cht-user-management/blob/9e4f3e561f5581700cc6fab6d1fa707a26499874/src/lib/cht-api.ts#L53

### PR DESCRIPTION
**Pull request by freddieptf**
Fixes #8 
Use axios to correctly encode the passed credentials

### CODE REVIEW

File: src/lib/cht-api.ts [hunk 1]
```diff
@@ -50,10 +50,15 @@ export class ChtApi {
...
     const COUCH_AUTH_COOKIE_NAME = 'AuthSession=';
     const protocol = authInfo.useHttp ? 'http' : 'https';
-    const sessionUrl = `${protocol}://${username}:${password}@${authInfo.domain}/_session`;
+    const sessionUrl = `${protocol}://${authInfo.domain}/_session`;
     const resp = await axios.post(sessionUrl, {
       name: username,
       password,
+    }, {
+      auth: {
+        username:username,
```
Comment (kennsippell) [inline src/lib/cht-api.ts:59]: can you use shorthand? 
```suggestion
        username,
```

**Review by kennsippell — APPROVED** [review]

**Comment by kennsippell** [comment]
Remember to bump package.json version via npm version patch or similar
