### PR TITLE
fix(#324): make MAX_SENTINEL_BACKLOG configurable

### LINKED ISSUE #324: Unable to DELETE CHP Areas using the UMT Tool.
Hello Medic Developers,
Please allow me to raise this issue here. So recently we are unable to DELETE CHP Areas using the UMT Tool.
Please find screenshots.

**Partner Name**: Living Goods
**Proposed URL**: https://users.echis.go.ke/
**ECHIS APP**:  https://kisumu-echis.health.go.ke/

Sample CHP Contact to be deleted - 98a4e96c-9242-542c-baf5-0afb27c56cf0

Image

console errors hitting the 'DELETE' Button

Image

### PR DESCRIPTION
**Pull request by freddieptf**
Fixes #324 
Not really a fix, but a way to configure the `MAX_SENTINEL_BACKLOG` so jobs don't get postponed, default value is still 7000

- Make `MAX_SENTINEL_BACKLOG` configurable
- Fixes undefined function error shown in browser logs
- Updates cht-conf to v6
- ~Merge operation now generates two jobs; one for the place and another for the primary contact~
- ~Updates tests~

### CODE REVIEW

File: src/lib/cht-api.ts [hunk 1]
```diff
@@ -186,6 +186,18 @@ export class ChtApi {
     return resp.data;
   }
 
+  async getDocs(ids: string[]): Promise<any> {
+    const url = 'medic/_bulk_get';
+    console.log('axios.get', url);
```
Comment (paulpascal) [inline src/lib/cht-api.ts]:
```suggestion
    console.log('axios.post', url);
```
?

File: src/worker/cht-conf-worker.ts [hunk 2]
```diff
@@ -20,20 +21,20 @@ export interface PostponeReason {
 
 export type JobResult = { success: boolean; message: string };
 
-export class ChtConfWorker {    
+export class ChtConfWorker {
   private static readonly DELAY_IN_MILLIS = 4 * 60 * 60 * 1000;       // 4 hours
   private static readonly MAX_TIMEOUT_IN_MILLIS = 4 * 60 * 60 * 1000; // 4 hours
   private static readonly MAX_CONCURRENCY = 1;              // Limit concurrency to 1 job at a time
-  private static readonly MAX_SENTINEL_BACKLOG = 7000;      // ensure we don't take down the server
+  private static readonly MAX_SENTINEL_BACKLOG = env.MAX_SENTINEL_BACKLOG ?? 7000;      // ensure we don't take down the server
```
Comment (paulpascal) [inline src/worker/cht-conf-worker.ts]: Should we need a casting her to safe the downstream comparisons ? (string vs number comparisons)

File: src/routes/manage-hierarchy.ts [hunk 3]
```diff
@@ -45,18 +45,18 @@ export default async function sessionCache(fastify: FastifyInstance) {
...
         chtApi
       );
       if (isConfirmed) {
-        await ManageHierarchyLib.scheduleJob(job);
+        await ManageHierarchyLib.scheduleJob(jobs);
         tmplData.success = true;
       } else {
         const warningInfo = await ManageHierarchyLib.getWarningInfo(
-          job,
+          jobs[0],
```
Comment (paulpascal) [inline src/routes/manage-hierarchy.ts]: **nit**: The warning info only considers the first job (place merge). If the primary contact merge could also produce warnings, those are silently ignored

File: test/lib/manage-hierarchy.spec.ts [hunk 4]
```diff
@@ -111,30 +114,47 @@ describe('lib/manage-hierarchy.ts', () => {
...
+      expect(primaryContact).to.have.property('jobName').that.equals('merge_[From Sub.C-H-U]_to_[To Sub.Destination]_primary_contacts');
+      expect(primaryContact).to.have.property('jobData').that.deep.include({
+        action: 'merge',
+        sourceId: 'cha_contact',
+        destinationId: 'cha2_contact',
+        instanceUrl: 'http://domain.com',
+        sessionToken: 'encoded-token',
+      });
+
     });
```
Comment (paulpascal) [inline test/lib/manage-hierarchy.spec.ts:124]: **nit**:
The test covers the case where both source and destination have primary contacts (generates 2 jobs) and the move case (1 job). But there's no test for a merge where only one place has a primary contact (or neither has one). The code handles it with filter(Boolean) and primaryContacts.length === 2.
Do you think a  test would be good to confirm the behavior ?

File: test/lib/manage-hierarchy.spec.ts [hunk 5]
```diff
@@ -111,30 +114,47 @@ describe('lib/manage-hierarchy.ts', () => {
       };
```
Comment (paulpascal) [inline test/lib/manage-hierarchy.spec.ts:111]: **nit**:
what happens when `getDocs` returns docs with contact as an `object` vs `string`?

I cld see the code handled both:
`typescripttypeof doc?.contact === 'string' ? doc.contact : doc?.contact?._id`

**Review by paulpascal — CHANGES_REQUESTED** [review]
Sounds good @freddieptf ✨
I have left some minor feedback.

**Comment by freddieptf** [comment]
@paulpascal no need for creating two merge jobs https://github.com/medic/cht-conf/releases/tag/v6.1.0

**Review by paulpascal — APPROVED** [review]
LGTM @freddieptf
