### PR TITLE
Fix search input for move, merge and delete forms

### LINKED ISSUE #282: Search input broken for move, merge and delete forms in v2.1.7
Broke the search input for Move, Merge and Delete forms in https://github.com/medic/cht-user-management/pull/257.

### PR DESCRIPTION
**Pull request by freddieptf**
Fixes #282 

Search input breaks without the correct hierarchy prefix. This fix makes sure the correct prefix is passes to the view.

### CODE REVIEW

File: src/routes/search.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default async function place(fastify: FastifyInstance) {
     return resp.view('src/liquid/components/search_results.html', {
       op,
       place,
-      div: 'div_hierarchy_' + hierarchyLevel.property_name,
+      div: `div_${dataPrefix}${hierarchyLevel.property_name}`,
```
Comment (kennsippell) [inline src/routes/search.ts:40]: seems a bit weird to include `div_` in the id

**Review by kennsippell — APPROVED** [review]
