### PR TITLE
fix(#236): update titleCase to handle hyphens and parenthesis

### LINKED ISSUE #160: Title Casing after hyphen
`Eor-Ekule CHU` is uploaded as `Eor-ekule Community Health Unit` but should be `Eor-Ekule Community Health Unit`

### LINKED ISSUE #236: Improper casing for names where part is in brackets
Observed: `Matopeni B (health Express)`
Expected: `Matopeni B (Health Express)`

### PR DESCRIPTION
**Pull request by Benmuiruri**
Update `titleCase` function to handle hyphens and parenthesis. 

Closes #236 
Closes #160

### CODE REVIEW

File: src/validation/validator-name.ts [hunk 1]
```diff
@@ -36,12 +36,34 @@ export default class ValidatorName implements IValidator {
...
+    }
+
+    const titleCase = (word: string) => word[0]?.toUpperCase() + word.slice(1);
+    const isRomanNumeral = /^[ivx]+$/i;
+
+    const processWord = (word: string) => {
+      if (word.match(isRomanNumeral)) {
+        return word.toUpperCase();
+      }
+      return word.includes('-')
```
Comment (kennsippell) [inline src/validation/validator-name.ts:50]: here we are splitting on a symbol, calling `processWord` for each word, and then rejoining. we are doing this again on line 62-65.  

what do you think of putting that pattern into a function `splitAndProcess(value, ' ')` and `splitAndProcess(value, '-')`?

File: src/validation/validator-name.ts [hunk 2]
```diff
@@ -36,12 +36,34 @@ export default class ValidatorName implements IValidator {
...
-    const words = value.toLowerCase().split(' ');
-    const titleCase = (word: string) => word[0].toUpperCase() + word.slice(1);
-    const isRomanNumeral = /^[ivx]+$/ig;
-    const titleCased = words
+    if (!value) {
+      return '';
+    }
+
+    const titleCase = (word: string) => word[0]?.toUpperCase() + word.slice(1);
+    const isRomanNumeral = /^[ivx]+$/i;
```
Comment (kennsippell) [inline src/validation/validator-name.ts:44]: its clear and useful to have the regex captured via a descriptive name.  it would be nice to do the same for the regex on lines 56-58.  in general, i find regex hard to parse and read and benefit from either a description or a comment

**Review by kennsippell — APPROVED** [review]

File: src/validation/validator-name.ts (hunk 1 above)
Comment (Benmuiruri) [reply src/validation/validator-name.ts]: Good catch.
